### PR TITLE
feat: add smtp login support

### LINKED ISSUE #9: Email notifications are likelly to be flagged as spam
Hello,
When sending out notifications about new sessions being created, the email messages are missing many standard message headers.
Here is the rspamd report when scanning such message:
```X-Rspamd-Report: MISSING_FROM(2) MISSING_DATE(1) MIME_GOOD(-0.1) MISSING_MID(2.5) MISSING_TO(2)```

### PR DESCRIPTION
**Pull request by cyrinux**
Add basic smtp login support, can fix https://github.com/tuffnerdstuff/hauk-snitch/issues/9 .

### CODE REVIEW

**Comment by tuffnerdstuff** [comment]
Thanks @cyrinux for fixing the merge conflicts so quickly, you were faster than me :) I'll just spin up hauk-snitch based on this branch to see if everything works and then I'll merge it right away. Thanks for your help!

**Comment by cyrinux** [comment]
Was not easy but it was my fault so happy to help :D

**Comment by tuffnerdstuff** [comment]
There was still an issue regarding referencing the config and the compiler (maybe I'm using an older go version) complained about untyped nil. I fixed it and master should now be fine. If you have time you can try to build it yourself :+1:

**Comment by cyrinux** [comment]
> There was still an issue regarding referencing the config and the compiler (maybe I'm using an older go version) complained about untyped nil. I fixed it and master should now be fine. If you have time you can try to build it yourself 👍

Good catch, thank you !

**Pull request merged**
